# fly.toml app configuration file generated for green-shadow-9504 on 2023-07-06T18:22:51-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-shadow-9504"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
