# fly.toml app configuration file generated for holy-resonance-2412 on 2023-07-14T17:11:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "holy-resonance-2412"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
